### ISSUE TITLE
cc

### ISSUE THREAD

**Issue by csdroit** [python-life/sendemail#1]
this script is very powerful and nice . but you set just the google mail ports it will not work in hotmail i think .

**Comment by csdroit** [comment]
IMAP

Server: imap-mail.outlook.com
SSL: true-implicit
Port: 993 (default)
User: pat@hotmail.com

POP3

Server: pop-mail.outlook.com
SSL: true-implicit
Port: 995 (default)
User: pat@hotmail.com

this can help you bro

**Comment by csdroit** [comment]
SMTP username: Your Gmail address
    SMTP password: Your Gmail password
    SMTP server address: smtp.gmail.com
    Gmail SMTP port (TLS): 587
    SMTP port (SSL): 465
    SMTP TLS/SSL required: yes

**Comment by Riadhcoding** [comment]
ok so what are you need bro

**Comment by Riadhcoding** [comment]
ah sorry bro i dont see your all message thank you for help me

**Comment by Riadhcoding** [comment]
But I did not understand how to apply it. Can you send me all the text
codes? like my tool

**Comment by csdroit** [comment]
okay I will post it and send the link of code.
